apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: mariadb-dc-rollout-rolebinding
  namespace: rhacm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: mariadb-dc-rollout-rolebinding
        spec:
          remediationAction: enforce # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          severity: high
          namespaceSelector:
            include: ["mariadb"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding # role binding must exist
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: dc-rollout-rolebinding
                subjects:
                - kind: Group
                  name: mariadb-operators # Name is case sensitive
                  apiGroup: rbac.authorization.k8s.io
                roleRef:
                  kind: Role #this must be Role or ClusterRole
                  name: dc-rollout-role # this must match the name of the Role or ClusterRole you wish to bind to
                  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: role-binding-placement-binding
  namespace: rhacm-policies
placementRef:
  name: dev-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: mariadb-dc-rollout-rolebinding
  kind: Policy
  apiGroup: policy.open-cluster-management.io
